# Generated by Django 2.2.3 on 2020-03-29 21:32

from django.db import migrations, models
import fooodie.models


class Migration(migrations.Migration):

    dependencies = [
        ('fooodie', '0003_auto_20200307_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to=fooodie.models.get_upload_filename),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
